version: 2.1
jobs:
  build:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: pip install --upgrade pip
      - run: pip install --upgrade setuptools
      - run: pip install -r requirements.txt
      - run: python -m unittest tests.test_array_sensing
